todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from todolist.views import  *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls', namespace='todolist')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

todoapp/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import ListView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers

from . import views 
from .utils import *

app_name = 'todolist'

router = routers.DefaultRouter()
router.register(r'tasks', views.TaskViewSet, basename='tasks')
router.register(r'important', views.ImportantTaskViewSet, basename='important')


urlpatterns = [
        path('', views.main_page, name='home'),
        path('tag/<slug:tag_slug>', views.main_page ,name='home_by_tags'),
        path('about/<int:task_id>', views.about, name='task_detail'),
        path('edit/<int:task_id>', views.edit_task, name='edit_task'),
        path('delete/<int:task_id>', views.delete_task, name='delete_task'),
        path('add-task', views.add_task, name='add_task'),
        path('login/', auth_views.LoginView.as_view(), name = 'login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('register/', views.register, name='register'),
        path('password-change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('todolist:password_change_done')), name='password_change'),
        path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "registration/password_change_done.html" ), name='password_change_done'),
        path('edit-profile/', views.edit_profile, name='edit_profile'),
        path('profile/', views.profile, name='profile'),
        path('api/v1/about/<slug:slug>/', views.TaskAboutViewSet.as_view({'get': 'retrieve', 'delete': 'destroy', 'put': 'update'}), name='api-task-about'),
        path('api/v1/', include(router.urls)),
        path('export-tasks/', views.export_tasks, name='export'),
        path('export-tasks/<int:task_id>/', views.export_tasks, name='export'),
        path('export-tasks-csv/', views.export_to_csv, name='export_csv'),
        path('export-tasks-csv/<int:task_id>/', views.export_to_csv, name='export_csv'),
        path('search/', views.task_search, name='search'),
]       

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

todoapp/todolist/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks', verbose_name='User')
    title = models.CharField(max_length=50, verbose_name='Title')
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL')
    description = models.TextField(verbose_name='Description')
    finish_date = models.DateTimeField(verbose_name='Date')
    finished = models.BooleanField(default=False, verbose_name='Finished')
    signif = models.ForeignKey('Importance', on_delete=models.PROTECT, null=True,
                               verbose_name='Importance')
    tag = TaggableManager()

    def __str__(self):
        return self.title
    
    def del_task(self):
        self.delete()
    
    class Meta:
        ordering = [ 'signif','finished', 'title', '-finish_date']

    def get_absolute_url(self):
        return reverse('todolist:task_detail' , args=[self.id])

class Importance(models.Model):
    class ImportantTypes(models.TextChoices):
        LOW = 'Low'
        MEDIUM = 'Medium'
        HIGH = 'High'
        CRITICAL = 'Critical'

    sygnif = models.CharField(max_length=100, db_index=True, verbose_name='Importance')
    importance = models.CharField(max_length=20, choices=ImportantTypes.choices, default=ImportantTypes.LOW)

    def __str__(self):
        return self.importance

    def get_absolute_url(self):
        return reverse()

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='%Y/%m/%d/', blank=True)

    def __str__(self):
        return f"{self.user.username}'s profile"

todoapp/todolist/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Task, Profile

class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'finish_date', 'finished', 'signif']
        widgets = {
            'finish_date':forms.DateTimeInput()
        }

class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'finish_date', 'signif']
        
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    rep_password = forms.CharField(label='Repeate password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_rep_password(self):
        cd = self.cleaned_data
        if len(cd['password']) < 6:
            raise forms.ValidationError("Too short password.\n It's should be at least 6 characters.")
        if cd['password'] != cd['rep_password']:
            raise forms.ValidationError("Passwords don't match")
        return cd['rep_password']
    
class SearchForm(forms.Form):
    query = forms.CharField()

todoapp/todolist/views.py
import json
import csv
from datetime import datetime
from django.http import HttpResponse
from django.core.serializers import serialize
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils.text import slugify
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVector
from rest_framework import permissions, viewsets, mixins
from rest_framework.response import Response

from .models import Task, Importance, Profile
from .forms import EditTaskForm, AddTaskForm, UserEditForm, \
                    ProfileEditForm, UserRegistrationForm, SearchForm

from .serializers import TaskSerializer

# Create your views here.
importances = ['Low', 'Medium', 'High', 'Critical']


def get_user(request):
    user_id = request.user.id
    user = User.objects.get(pk=user_id)
    return user

@login_required(login_url='login/')
def main_page(request, tag_slug=None):
   
    title = 'Todo'
    user = get_user(request)
    
    tag = None
    tasks = Task.objects.filter(user=user)
    if request.method == 'GET':
        query = request.GET.get('query')
        if query:
            return redirect('search')
        
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        tasks= Task.objects.filter(tag__in = [tag])
    paginator = Paginator(tasks, 6)
    page_number = request.GET.get('page', 1)
    try:
        tasks = paginator.page(page_number)

    except EmptyPage:
        tasks = paginator.page(paginator.num_pages)

    except PageNotAnInteger:
        tasks = paginator.page(1)

    return render(request, 'todolist/index.html', {"title" : title, "tasks" : tasks, "tag":tag} )

def about(request, task_id):
    title = 'About task'

    task = get_object_or_404(Task, id=task_id)

    return render(request, 'todolist/detail.html', {'task':task,
                                                    'title':title})

def edit_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    
    sent = False
    
    if request.method == 'POST':
        form = EditTaskForm(request.POST, instance=task)
        if form.is_valid():
            cd = form.cleaned_data
            slug = slugify(cd['title'])
            task.title = cd['title']
            task.slug = slug
            task.description = cd['description']
            task.finish_date = cd['finish_date']
            task.finished = cd['finished']
            task.signif = Importance.objects.get(pk=request.POST['signif'])
            task.save()
            sent = True
        return redirect(task, task_id=task.id)
    else:
        form = EditTaskForm(instance=task)

    return render(request, 'todolist/edit_task.html', {
        'sent':sent,
        'form':form,
        'task': task,
        'importances':importances
    })

def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id)

    if request.method == 'POST':
        task.del_task()
       
        return redirect('todolist:home')
    return render(request, 'todolist/delete_task.html')
    
def add_task(request):
    sent = False
    user = get_user(request)
    print(request.user.id)
    if user is not None:  # Проверка наличия пользователя
        if request.method == 'POST':
            form = AddTaskForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                slug = slugify(cd['title'])
                title = request.POST['title']
                description = request.POST['description']
                finish_date = request.POST['finish_date']
                finished = False
                signif = Importance.objects.get(pk=request.POST['signif'])
                
                task = Task(title=title, slug=slug, description=description, finish_date=finish_date,
                            finished=finished, signif=signif, user=user)
                task.save()
                sent = True
                return render(request, 'todolist/new_task.html', {'form':form, 'task':task, 'sent':sent})
        
        else:
            form = AddTaskForm()
        return render(request, 'todolist/new_task.html', {'form': form, 'sent': sent})
    else:
       
        return HttpResponse("User not found.")
    
@login_required(login_url='login/')
def edit_profile(request):
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('todolist:home')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'todolist/edit_profile.html', { 'user_form':user_form,
                                                                'profile_form':profile_form})

@login_required(login_url='login/')                                                                
def profile(request):
    user_id = request.user.id
    complete_tasks = Task.objects.filter(finished=True)
    uncomlete_tasks = Task.objects.filter(finished=False)
    profile_data = Profile.objects.get(pk=user_id)
    return render(request, 'todolist/profile.html', {
        'ctasks':complete_tasks,
        'unctasks':uncomlete_tasks,
        'profile_data': profile_data,
    })

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            return render(request, 'todolist/register_done.html', {'new_user': new_user})

    else:
        form = UserRegistrationForm()
    return render(request, 'todolist/register.html', {
        'user_form':form,
    })

def export_tasks(request, task_id=None):
    user = get_user(request)
    
    if task_id is None:
        file_name = f'tasks of {user.username}.json'
        data = Task.objects.filter(user=user)
    else:
        data = Task.objects.filter(user=user, pk=task_id)
        file_name = f'task{task_id} of {user.username}.json'

    serialized_data = serialize('json', data) 
    data_list = json.loads(serialized_data)

    for item in data_list:
                
        fd = datetime.fromisoformat(item['fields']['finish_date'].replace('Z', '+00:00')) 
        item['fields']['finish_date'] = fd.strftime('%Y-%m-%d %H:%M:%S')

    response = HttpResponse(content_type='application/json') 
    response['Content-Disposition'] = f'attachment; filename="{file_name}"'
    json.dump(data_list, response, ensure_ascii=False)
    return response

def export_to_csv(request, task_id = None):
    user = get_user(request)
    
    if task_id is None:
        file_name = f'tasks of {user.username}.csv'
        data = Task.objects.filter(user=user).only('title', 'description', 'finish_date', 'finished', 'signif')
    else:
        data = Task.objects.filter(user=user, pk=task_id).only('title', 'description', 'finish_date', 'finished', 'signif')
        file_name = f'task{task_id} of {user.username}.csv'

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{file_name}"'
    
    writer = csv.writer(response)
    writer.writerow(['Title', 'Description', 'Finish_date', 'Finished', 'Signif'])
    for d in data:
        writer.writerow([d.title, d.description, d.finish_date, d.finished, d.signif])

    return response

def task_search(request):
   
    user = get_user(request)
    query = request.GET.get('query')
    result = []

    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Task.objects.annotate(search=SearchVector('title', 'description', 'tag')
                                            ).filter(user=user, search=query)
    return render(request, 'todolist/search.html', {'srch_form':form,                                             
                                                   'query':query,
                                                   'results':results})

# Viewsets

class TaskViewSet( viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    queryset = Task.objects.all().order_by('title')
    permission_classes = [permissions.IsAuthenticated,permissions.IsAdminUser]

class ImportantTaskViewSet(viewsets.ModelViewSet):
    serializer_class = TaskSerializer
    signif = Importance.objects.filter(Q(importance='High') | Q(importance='Critical'))
    queryset = Task.objects.filter(signif__in=signif)
    permission_classes = [permissions.IsAuthenticated,permissions.IsAdminUser]

class TaskAboutViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    lookup_field = 'slug'

    def get_queryset(self):
        task_slug = self.kwargs.get('slug')
        queryset = self.queryset.filter(slug=task_slug)
        return queryset
            
        


        

todoapp/todolist/templates/todolist/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{{title}}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'todolist/css/style.css' %}">
</head>
<body>
  <header>
    <h1 class="title-name">My ToDo App</h1>
    
    {% if request.user.is_authenticated %}

      <span class="user"> Hi <a href="{% url 'todolist:profile' %}">{{request.user.username|capfirst}}</a> |
        <a href="{% url 'todolist:logout' %}">Logout</a>
      </span>
    {% endif %}
    
  </header>

  <content>
    {% block content %}
    {% endblock %}
    
  </content>  
  <footer>
    <div class="cont-foot">
      <p>&copy; 2023 My ToDo App. All rights reserved.</p>
    </div>
  </footer>
  <script src="{% static 'todolist/js/app.js' %}"></script>
</body>
</html>

todoapp/todolist/templates/todolist/delete_task.html
{% extends "todolist/base.html" %}

{% block content%}
    <div style="margin-left: 20%; font-size: 20px;">
    <h2>Delete Task</h2>

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this task?</p>
        <input type="submit" value="Delete Task">
    </form>
    </div>
{% endblock%}

todoapp/todolist/templates/todolist/detail.html
{% extends "todolist/base.html" %}


{% block content %}

    <style>
        p {
            font-size: 25px;
            margin-left: 20px;
            font-weight: bold;
        }
        .link-home {
            margin-left: 30px;
            color: #33bcde;
            text-decoration: none;
            font-size: 20px;
        }

        .link-home:visited {
            margin-left: 30px;
            color: #32a9c7;
        }

        .link-home:hover {
            text-decoration: underline;
        }

        
    </style>
    <div class="menu-tools">
        <a href="{%url 'todolist:home' %}" class="link-home">Back to main list</a>
        <a href="{% url 'todolist:export' task.id %}">Export task</a>
        
        <div class="edit">
            <a href="{% url 'todolist:edit_task' task.id %}">Edit task</a>
        </div>

        <div class="delete">
            <a href="{% url 'todolist:delete_task' task.id %}">Delete task</a>
        
        </div> 
    </div>   
    <p>Task: {{task.title }}</p>
    <hr/>
    <p>Description: {{task.description}}</p>
    <hr/>
    <p>Finish date: {{task.finish_date}}</p>
    <hr/>
    <p>Status:
        {% if task.finished%}
            ✅
        {%else %}
            ❌
        {%endif%}
    </p>
    <hr/>
    <p>Significance: {{task.signif}}</p>
    <hr/>
    <p>Tags: {{task.tag.all|join:", "}}</p>

{% endblock %}

todoapp/todolist/templates/todolist/edit_profile.html
{% extends "todolist/base.html" %}

{% block content %}
    <div class="edit-profile">
        <h1>Form to edit profile</h1>
        <p>Use this form to edit your profile:</p>
        {% with user_form as user %}
        
        {% with profile_form as profile %}
        
        <form method="post" enctype="multipart/form-data">
            {{user.as_p}}
            {{profile.as_p}}
            {% csrf_token %}
            <p><input type="submit" value="Save changes"></p>

        </form>
        {% endwith %}
        {% endwith %}
    </div>
{% endblock %}

todoapp/todolist/templates/todolist/edit_task.html
{% extends "todolist/base.html" %}


{% block content%}
{% if sent %}
<a href="{% url 'todolist:task_detail' task.id%}">Go back to edited task</a>
{% else %}
<h1 style="text-align: center;">Edit Task</h1>
<form method="POST">
    {% csrf_token %}
    <div class="form-container">
   
        {{ form.as_p}}
        <input type="submit" value="Accept" class="form-submit">
    </div>
</form>
{% endif %}


{% endblock %}

{% for field in form %}
    <div>
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}

todoapp/todolist/templates/todolist/index.html
{% extends 'todolist/base.html' %}


{% block content %}
    <a class="new-task" href='{% url "todolist:add_task" %}'>Add new task</a>   
    <a class="export" href='{% url "todolist:export" %}'>Export tasks</a>
    <a class="export-csv" href="{% url 'todolist:export_csv' %}">Export tasks to csv</a>
{% if tasks %}
    <div class="ordering">
        <select id='ordering'name="ordering">
            <option >Order by importance</option>
            <option >Order by finished</option>
            <option >Order by not finished</option>
        </select>
    </div>
    <div class="search">
        <form method="get" action="{% url 'todolist:search' %}">
           
            <input type="text" name="query"/>
            <button  type="submit" value="Search...">Search</button>
        </form>
    </div>

    <div class="container">
        
        {% if tag %}
            <h2>Tasks tagged with tag {{ tag.name }}. Go back to <a class="tag-main-page" href="{% url 'todolist:home' %}">main page</a>.</h2>
        {% else %}
            <h2>Tasks</h2>
        {% endif %}
        <div class="tasks-list">
        {% for task in tasks %}
        <div class="tasks-cont">
        <div class="task-body">
            <div class="task-area">
                <p class="task-title"><a href="{{task.get_absolute_url}}" class="link-title">{{task.title}}</a></p>
                <p class="task-desc">Task: {{task.description|truncatewords:10}}</p>
                {% if task.signif.importance == "Low"%}
                    <p class="task-finish-date"><span class="finish-low">Finish date: {{task.finish_date}}</span></p>
                {% elif task.signif.importance == "Medium"%}
                    <p class="task-finish-date"><span class="finish-medium">Finish date: {{task.finish_date}}</span></p>
                {% elif task.signif.importance == "High"%}
                    <p class="task-finish-date"><span class="finish-high">Finish date: {{task.finish_date}}</span></p>
                {% else %}
                    <p class="task-finish-date"><span class="finish-critical">Finish date: {{task.finish_date}}</span></p>
                {%endif%}
                {% if task.finished%}
                    <p class="task-finished">Status: ✅</p>
                {%else %}
                    <p class="task-finished">Status: ❌</p>
                {%endif%}
                {% if task.tag.all%} 
                    <p class="task-desc">Tags: 
                        {% for tag in task.tag.all %}
                        <a class = "link-tag" href="{% url 'todolist:home_by_tags' tag.slug %}">{{tag.name}}</a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                {% else %}
                    <p class="task-desc">Tags: no tags</p>
                {% endif %}

            </div>
        </div>
        </div>
        {% endfor %}
        </div>
        
        
    </div>
    {% include "todolist/pagination.html" with page=tasks%}
{% else %}
<p>No one tasks added</p>
{% endif %}  

{% endblock %}

todoapp/todolist/templates/todolist/new_task.html
{% extends "todolist/base.html"%}

{%block content %}
{% if sent %}
<p style="text-align: center;">New task "{{task.title}} added to list</p>
<a style="text-align: center;" href="{% url 'todolist:home' %}">Back to list</a>

{% else %}

<h2>Add new task</h2>

    <form method="post">
        {% csrf_token %}
    
        <div class="form-container">
   
            {{ form.as_p}}
            <input type="submit" value="Accept" class="form-submit">
        </div>
    </form>
{% endif%}

{% endblock%}


{% for field in form %}
    <div>
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}

todoapp/todolist/templates/todolist/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

todoapp/todolist/templates/todolist/profile.html
{% extends "todolist/base.html" %}
{% load static %}
{% block content %}
    <div class="profile">
        <div class="profile-user">
            <h3>Your profile</h3>
            <div class="profile-data">
                <p>Username: {{request.user.username}}</p> 
                
                {% if request.user.email %}
                <p>Email: {{request.user.email}}</p>
                    
                {% else %}
                <p>Email: not specified</p>
                    
                {% endif %}

                {% if request.user.first_name %}
                <p>First name: {{request.user.first_name}}</p>
                    
                {% else %}
                <p>First name: not specified</p>
                    
                {% endif %}

                {% if request.user.last_name %}
                <p>Last name: {{request.user.last_name}}</p>
                    
                {% else %}
                <p>Last name: not specified</p>
                    
                {% endif %}

                {% if profile_data.date_of_birth %}
                <p>Date of birth: {{profile_data.date_of_birth}}</p>
                    
                {% else %}
                <p>Date of birth: not specified</p>
                    
                {% endif %}
                
            </div>

            <img alt="Profile image" src="{{profile_data.photo.url}}">
            <p class="profile-nav"><a href="{% url 'todolist:edit_profile' %}">Edit profile</a>. <a href="{% url 'todolist:home' %}">Main list</a></p>
        </div>  
        
        <div class="profile-tasks">
            <div class="profile-wrapper">
                <div class="finished-tasks">
                    <div class="title">
                            <span>Completed tasks</span>
                    </div>
                    <div class="task-list">
                        <ul>
                            {% for task in ctasks %}
                                <li><a target="_blank" href="{{task.get_absolute_url}}">{{task.title}} - {{task.finish_date}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="unfinished-tasks">
                    <div class="title">
                        <span>Unfinished tasks</span>   
                    </div>
                    <div class="task-list">
                        <ul>
                            {% for task in unctasks %}
                                <li><a target="_blank" href="{{task.get_absolute_url}}">{{task.title}} - {{task.finish_date}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
        </div>
        </div>
    </div>
{% endblock %}

todoapp/todolist/templates/todolist/register.html
{% extends "todolist/base.html" %}

{% block content %}
 <div class="edit-profile">
    <h1>Form to sign up</h1>
    <form method="post">
        {{user_form.as_p}}
        {% csrf_token %}
        <p><input type="submit" value="Create an account"/></p>
    </form>
</div>
{% endblock %}

todoapp/todolist/templates/todolist/register_done.html
{% extends "todolist/base.html" %}

{% block content %}
<div class="edit-profile">
    <h1>Welcome to our site {{new_user.first_name}}</h1>
    <p>Your account was successfully created and you can sign in using this <a href="{% url 'todolist:login' %}">form</a></p>
</div>
{% endblock %}

todoapp/todolist/templates/todolist/search.html
{% extends "todolist/base.html" %}

{% block content %}
<div class="main_block">
    {% if results %}
    <h1>Search results:</h1>
    <h3>
        {% with results.count as tot_res %}
            Found {{tot_res}} result{{ tot_res|pluralize }} 
        {% endwith %}
    </h3>
    {% for res in results %}
        <p><a href="{{res.get_absolute_url}}">{{res.title}}</a></p>

    {% endfor %}
    {% else %}
    <p>There are no results for your query.</p>
    {% endif %}
    <p><a href="{% url 'todolist:home' %}">Back to main list</a></p>
    

</div>
{% endblock %}